#syntax=quay.io/vdemeest/buildkit-tekton
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: buildkit-tekton-on-pull-request
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/task: "[git-clone, golang-test, .tekton/tasks/buildah.yaml]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
spec:
  params:
    - name: repo_url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
    tasks:
      - name: fetch
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
        taskSpec:
          params:
          - name: url
            type: string
          - name: revision
            type: string
          steps:
          - image: bash:latest
            script: |
              echo URL: $(params.url)
              echo Revision: $(params.revision)
