apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: test
spec:
  pipelineSpec:
    tasks:
      - name: hello
        taskSpec:
          steps:
          - image: hello
            image: bash:latest
            script: |
              echo hello world
      - name: bye
        runAfter: [ hello ]
        taskSpec:
          steps:
          - image: bye
            image: bash:latest
            script: |
              echo bye world
